[package]
name = "ibowasp"
version = "0.1.0"
authors = ["Mesa CI <mesa@example.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.9.18"
serde_json = "*"

[[bin]]
name = "ibowasp"
path = "main.rs"
